# --------------------- #
#    Generation File    #
# --------------------- #

# Other generation files to import. (Example: intensive_apps -> ~/.config/rebos/imports/intensive_apps.toml)
imports = [
    # "intensive_apps",
]

# Packages to be installed via the native package manager.
[managers.system]
items = [
    "git",
    "nvim",
    "hyprland",
    "kitty",
    "stow",
    "docker",
    "docker-compose",
    "gnome-disk-utility",
    "zen-browser-bin",
    "gauntlet-bin",
    "oh-my-posh-bin",
    "zoxide",
    "zsh",
    "atuin",
    "pay-respects-bin",
    "blueman",
    "blueberry",
    "playerctl",
    "eza",
    "fzf",
    "layan-gtk-theme-git",
    "nwg-look",
    "keyd",
    "proton-authenticator-bin",
    "wireguard-tools",
    "proton-vpn-gtk-app",
    "aylurs-gtk-shell-git",
    "otf-firamono-nerd",
    "gnome-disk-utility",
    "ntfs-3g",
]

# Packages to be installed via Flatpak.
[managers.flatpak]
items = [
    # "com.github.tchx84.Flatseal",
]

# Packages to be installed via Cargo.
[managers.cargo]
items = [
    # "bacon",
]
