# Apps
unbind = SUPER, SPACE
bindd = SUPER, SPACE, Omarchy menu, exec, vicinae toggle

unbind = SUPER, Q
bind = SUPER,Q,  exec, ghostty

unbind = SUPER, F
bind = SUPER,F,  exec, vicinae vicinae://launch/applications/zen

# Navigation
unbind = SUPER, C
bind = SUPER,C, killactive

unbind = SUPER, H
bind = SUPER,H, movefocus, l

unbind = SUPER, J
bind = SUPER,J, movefocus, d

unbind = SUPER, K
bind = SUPER,K, movefocus, u

unbind = SUPER, L
bind = SUPER,L, movefocus, r
