
add = "sudo systemctl enable --now #:?" # Example: sudo apt install #:?
remove = "paru -Rns --noconfirm #:?" # Example: sudo apt remove #:?

plural_name = "system services"

hook_name = "system_services" # This is used in hooks. (Example: post_system_packages_add)

# ------------------------------- #
#    Additional configuration.    #
# ------------------------------- #

# many_args = BOOL: Can you supply many items as an argument? Example: 'sudo apt install git vim wget'

[config]
many_args = true
